
export const triageTableHeadersInitialState = [
    {
        index: 0,
        displayName: '',
        name: '',
        sortable: false,
        sortAsc: false,
        sortDesc: false,
        filterable: false,
        filterableType: 'search',
        filters: '',
        classes: 'childrenExpand'
    },
    {
        index: 1,
        displayName: 'Customer',
        name: 'customer',
        sortable: true,
        sortAsc: false,
        sortDesc: false,
        filterable: true,
        filterableType: 'search',
        filters: '',
        classes: 'datacell'
    },
    {
        index: 2,
        displayName: 'Style Number',
        name: 'stylenumber',
        sortable: true,
        sortAsc: false,
        sortDesc: false,
        filterable: true,
        filterableType: 'search',
        filters: '',
        classes: 'datacell'
    },
    {
        index: 3,
        displayName: 'Triage Owner',
        name: 'triageowner',
        sortable: true,
        sortAsc: false,
        sortDesc: false,
        filterable: true,
        filterableType: 'select',
        filters: '',
        classes: 'datacell'
    },
    {
        index: 4,
        displayName: 'Owner',
        name: 'owner',
        sortable: true,
        sortAsc: false,
        sortDesc: false,
        filterable: true,
        filterableType: 'select',
        filters: '',
        classes: 'datacell'
    },
    {
        index: 5,
        displayName: 'Workload',
        name: 'workload',
        sortable: false,
        sortAsc: false,
        sortDesc: false,
        filterable: false,
        filterableType: 'search',
        filters: '',
        classes: 'datacell'
    },
    {
        index: 6,
        displayName: 'Buildtime',
        name: 'buildtime',
        sortable: false,
        sortAsc: false,
        sortDesc: false,
        filterable: false,
        filterableType: 'search',
        filters: '',
        classes: 'datacell'
    },
    {
        index: 7,
        displayName: 'Sales Order',
        name: 'salesorder',
        sortable: true,
        sortAsc: false,
        sortDesc: false,
        filterable: true,
        filterableType: 'search',
        filters: '',
        classes: 'datacell'
    },
    {
        index: 8,
        displayName: 'SO Line Item',
        name: 'solineitem',
        sortable: true,
        sortAsc: false,
        sortDesc: false,
        filterable: true,
        filterableType: 'search',
        filters: '',
        classes: 'datacell'
    },
    {
        index: 9,
        displayName: 'Same As',
        name: 'sameas',
        sortable: false,
        sortAsc: false,
        sortDesc: false,
        filterable: false,
        filterableType: 'search',
        filters: '',
        classes: 'datacell'
    },
    {
        index: 10,
        displayName: 'Triage Complete Date',
        name: 'triagecompletedate',
        sortable: false,
        sortAsc: false,
        sortDesc: false,
        filterable: false,
        filterableType: 'search',
        filters: '',
        classes: 'datacell'
    },
    {
        index: 11,
        displayName: 'Design Complete Date',
        name: 'designcompletedate',
        sortable: false,
        sortAsc: false,
        sortDesc: false,
        filterable: false,
        filterableType: 'search',
        filters: '',
        classes: 'datacell'
    },
    {
        index: 12,
        displayName: 'Due Date',
        name: 'duedate',
        sortable: false,
        sortAsc: false,
        sortDesc: false,
        filterable: false,
        filterableType: 'search',
        filters: '',
        classes: 'datacell'
    },
    {
        index: 13,
        displayName: 'Triage Complete',
        name: 'triagecomplete',
        sortable: false,
        sortAsc: false,
        sortDesc: false,
        filterable: false,
        filterableType: 'search',
        filters: '',
        classes: 'datacell'
    },
    {
        index: 14,
        displayName: 'Delete',
        name: 'delete',
        sortable: false,
        sortAsc: false,
        sortDesc: false,
        filterable: false,
        filterableType: 'search',
        filters: '',
        classes: 'datacell'
    }
]